### ISSUE TITLE
Table markdown syntax

### ISSUE THREAD

**Issue by quangnhat185** [mtc-20/CheatSheets#1]
|  Image     | Dog| Great Cat | Blur | Note                                |
| :---------: |:-----:| :--------: |:-----: |:---------------------------:|
| 1           |  ✔  |            |        | Pitbull with strange color          |
| 2           |       |            |  ✔   |                                                   |
| 3           |       |  ✔       |  ✔   | Lion in the zoo                          |
| 4           |       |  ✔       |        | Panther  behind the tree           |
| ...           | ...   | ...         | ...      | ...                                              |
| **Total %**  | 8%    | 43%        | 61%    |                                 |

**Comment by mtc-20** [comment]
Thanks for the code. Closing the issue
